/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_appsync_graphqlEndpoint": "https://dijiv6o6mndefgokn3uvnezpd4.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dsbqziefnvhdxov76kfeieelsy",
    "aws_cognito_identity_pool_id": "eu-west-3:68f7ee6e-dc4b-42c3-a1cd-f0d16e832913",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_xTUsrZI9N",
    "aws_user_pools_web_client_id": "3ar6l29ginlnjroscetreoaqb5",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "adrianacampsbdbf61de1d794c2085b822f76e214d17174813-dev",
    "aws_user_files_s3_bucket_region": "eu-west-3"
};


export default awsmobile;
